version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: W-EDAX.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_ENVIRONMENT=Development